# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-18 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeblob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='timeblob.Project'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='timeblob.Task'),
        ),
    ]
