# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-20 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeblob', '0002_allowing_blanking_of_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeblob.Project'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 21, 24, 45, 50221, tzinfo=utc)),
        ),
    ]
