# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-20 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeblob', '0003_auto_20160720_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 21, 25, 10, 169689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeblob.Task'),
        ),
    ]
