# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-20 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeblob', '0004_auto_20160720_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 21, 25, 53, 881439, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 21, 25, 53, 881194, tzinfo=utc)),
        ),
    ]
