# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-08-20 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeblob', '0005_auto_20160720_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
